### ISSUE TITLE
Unable to install @nrwl/expo

### ISSUE THREAD

**Issue by mdodell** [nrwl/nx-expo#5]
It looks like @nrwl/expo isn't public on the NPM registry. Is there any date that it might be ready to go for Alpha?

**Comment by juristr** [comment]
Hey, we moved the development of `@nrwl/expo` into the Nx labs repo => https://github.com/nrwl/nx-labs.

We're wrapping up the last things and should have a beta version soon on npm, so stay tuned :)

**Comment by mdodell** [comment]
> Hey, we moved the development of `@nrwl/expo` into the Nx labs repo => https://github.com/nrwl/nx-labs.
> 
> 
> 
> We're wrapping up the last things and should have a beta version soon on npm, so stay tuned :)

Is there an issue for the beta release I can subscribe to?
